projects:
  bwfsurveybetadev-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/shared/services/api.service.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: bfnddhipvvaallvpkd3uffhvlq
        maxDepth: 2
extensions:
  amplify:
    version: 3
